---
- name: Установка Jenkins на jenkins-сервере
  hosts: jenkins_ec2   # Группа/хосты для Jenkins
  become: yes
  tasks:
    - name: Установить необходимые зависимости
      apt:
        name:
          - openjdk-11-jdk
          - curl
          - gnupg
          - ca-certificates
        state: present
        update_cache: yes

    - name: Добавить ключ репозитория Jenkins
      get_url:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        mode: '0644'

    - name: Добавить репозиторий Jenkins
      apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/"
        state: present
        update_cache: yes

    - name: Установить Jenkins
      apt:
        name: jenkins
        state: present

    - name: Убедиться, что Jenkins запущен
      service:
        name: jenkins
        state: started
        enabled: yes


- name: Установка Apache на другом EC2-сервере
  hosts: apache_ec2     # Группа/хосты для Apache
  become: yes
  tasks:
    - name: Установить Apache
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Убедиться, что Apache запущен
      service:
        name: apache2
        state: started
        enabled: yes
